version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    ports:
      - '5432:5432'
    expose:
      - '5432'